# XBox 360 wireless joystick with xboxdrv driver
axis_linear: 1 # Forward/Back
scale_linear: 0.7
scale_linear_turbo: 1.5

axis_angular: 0 # Twist
scale_angular: 0.8

enable_button: 4 # Left button
enable_turbo_button: 6 # "back" button
